# NGINX mit einer benutzerdefinierten Konfiguration
FROM nginx:latest

# Kopiere die benutzerdefinierte Konfiguration
# COPY ../nginx/default.conf /etc/nginx/conf.d/

# Kopiere die Inhalte in das NGINX-HTML-Verzeichnis
COPY dist /usr/share/nginx/html