export const DEMO_RESULTS = {
  events: [
    {
      id: 1,
      name: 'Demo Hackathon 2024',
      start_time: 1727766000,
      end_time: 1727884800,
    },
    {
      id: 2,
      name: 'Demo Hackathon 2025',
      start_time: 1750834800,
      end_time: 1750953600,
    },
  ],
  profiles: [
    {
      id: 1,
      name: 'Dummy 1',
      email: '',
      telephone: '',
      role_id: 6,
      avatar_url: '/assets/avatars/avatar_1.png',
    },
    {
      id: 2,
      name: 'Dummy 2',
      email: '',
      telephone: '',
      role_id: 6,
      avatar_url: '/assets/avatars/avatar_1.png',
    },
    {
      id: 3,
      name: 'Dummy 3',
      email: '',
      telephone: '',
      role_id: 6,
      avatar_url: '/assets/avatars/avatar_1.png',
    },
  ],
  projects: [
    [
      {
        event_id: 1,
        id: 1,
        status_id: 3,
        idea: 'Demo Project 1',
        description: 'This is a demo project description.',
        team_name: 'Demo Team 1',
        goal: 'Demostrate of this Tool',
        components: 'Computer, VS Code, GitHub',
        skills: 'JavaScript, TypeScript, React',
        initiators: [{ id: 1, name: 'Dummy 1', avatar_url: '/assets/avatars/avatar_1.png' }],
        participants: [{ id: 2, name: 'Dummy 2', avatar_url: '/assets/avatars/avatar_1.png' }],
      },
    ],
    [
      {
        event_id: 2,
        id: 2,
        status_id: 1,
        idea: 'Demo Project 2',
        description: 'This is a demo project description.',
        team_name: 'Demo Team 2',
        goal: 'Demostrate of this Tool',
        components: 'Computer, VS Code, GitHub',
        skills: 'JavaScript, TypeScript, React',
        initiators: [{ id: 1, name: 'Dummy 1', avatar_url: '/assets/avatars/avatar_1.png' }],
        participants: [{ id: 2, name: 'Dummy 2', avatar_url: '/assets/avatars/avatar_1.png' }],
      },
      {
        event_id: 2,
        id: 3,
        status_id: 1,
        idea: 'Demo Project 1',
        description: 'This is a demo project description.',
        team_name: 'Demo Team 1',
        goal: 'Demostrate of this Tool',
        components: 'Computer, VS Code, GitHub',
        skills: 'JavaScript, TypeScript, React',
        initiators: [{ id: 3, name: 'Dummy 1', avatar_url: '/assets/avatars/avatar_1.png' }],
        participants: [],
      },
    ],
  ],
};
